import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use",
};

const LAST_UPDATED = "2026-06-23";

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <div className="mb-10">
        <p className="text-[10px] font-bold tracking-[0.3em] uppercase text-accent mb-3">Legal</p>
        <h1 className="text-2xl font-light text-gray-900 tracking-tight mb-2">Terms of Use</h1>
        <p className="text-xs text-gray-300">Last updated: {LAST_UPDATED}</p>
      </div>

      <div className="space-y-8 text-xs text-gray-600 leading-relaxed">

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">1. The Service</h2>
          <p>
            Proper Paper Audit ("PPA") is a conceptual audit engine for research papers and manuscripts.
            It provides automated audit reports based on submitted text. It is not a writing assistant,
            peer reviewer, or publication guarantee.
          </p>
        </section>

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">2. Constitutional Constraint</h2>
          <p>
            No authors are scored. Proper Paper Audit audits texts, concepts, risks, and revision
            conditions — never the worth of the writer. Score is not judgment. It is an entry point
            for revision. This constraint is non-negotiable and applies to all uses of the service
            and its reports.
          </p>
        </section>

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">3. Acceptable Use</h2>
          <p className="mb-3">You may use this service to:</p>
          <ul className="space-y-2 pl-4 mb-3">
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Audit your own papers, drafts, or manuscripts for revision purposes.</span></li>
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Use audit reports as entry points for your own editorial judgment.</span></li>
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Audit texts you have permission to submit.</span></li>
          </ul>
          <p className="mb-3">You may not use this service to:</p>
          <ul className="space-y-2 pl-4">
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Score, rank, or evaluate the worth of authors or researchers.</span></li>
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Use audit scores as official publication decisions, hiring criteria, or institutional evaluations.</span></li>
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Submit papers belonging to others without their knowledge.</span></li>
            <li className="flex gap-3"><span className="text-gray-200 shrink-0">—</span><span>Automate submission at scale in a way that misrepresents the audit as authoritative review.</span></li>
          </ul>
        </section>

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">4. Audit Reports</h2>
          <p>
            Audit reports are generated by AI (GPT-4o) and may fall back to a mock audit when the
            API is unavailable. Reports are diagnostic tools for revision, not authoritative assessments.
            We make no guarantee of accuracy, completeness, or fitness for any specific publication venue.
          </p>
        </section>

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">5. Intellectual Property</h2>
          <p>
            You retain all rights to the text you submit. The audit report generated is provided
            for your personal use. The PPA audit methodology, scoring framework, and constitutional
            principles are the intellectual property of Plato Design.
          </p>
        </section>

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">6. Limitation of Liability</h2>
          <p>
            The service is provided "as is" without warranty of any kind. We are not liable for
            editorial decisions made on the basis of audit reports, for publication rejections,
            or for any consequential damages arising from use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-[10px] font-bold tracking-[0.2em] uppercase text-gray-300 mb-3">7. Changes to These Terms</h2>
          <p>
            We may update these terms. Continued use after changes constitutes acceptance.
            Material changes will be reflected in the "Last updated" date above.
          </p>
        </section>

      </div>
    </div>
  );
}
